export interface Transfer {
  name: string;
  phone: string;
  email: string;
  contactTime: string;
  contactChannel: string;
  problem: string;
  steps: string;
  pinVerification: string;
  emailVerification: string;
  transferReason: string;
}

export class Transfer {
  constructor(
    public name: string = "",
    public phone: string = "",
    public email: string = "",
    public contactTime: string = "",
    public contactChannel: string = "",
    public problem: string = "",
    public steps: string = "",
    public pinVerification: string = "",
    public emailVerification: string = "",
    public transferReason: string = "",
  ) {
    // this.name = "John Doe";
    // this.phone = "123123123";
    // this.email = "john@test.com";
    // this.problem = "Customer was reporting none of his users could receive emails";
    // this.steps = "-Advised MX records aren't pointing to Google \n -Guided through DNS host on adding G Suite MX records \n -Advised 24-72 hours propagation time";
    // this.reason = "Complex issue";
    // this.pinVerification = `PIN VALID: 
    // Specified PIN is Valid. It was generated by googleapps@psotago.org.nz with scope AS_SUPER_ADMIN. It expires at: 
    // 2019-Jul-07 22:51:29 L`;
  }
}
