export interface Inbound {
  domain: string;
  name: string;
  phone: string;
  email: string;
  reason: string;
  identification: string;
  reasoning: string;
  featureIdea: string;
  secondary: string;
  resolution: string;
  pinVerification: string;
  emailVerification: string;
  followupDate: string;
  status: string;
}

export class Inbound {
  constructor(
    public domain: string = "",
    public name: string = "",
    public phone: string = "",
    public email: string = "",
    public reason: string = "",
    public identification: string = "",
    public reasoning: string = "",
    public featureIdea: string = "",
    public secondary: string = "",
    public resolution: string = "",
    public pinVerification: string = "",
    public emailVerification: string = "",
    public followupDate: string = "",
    public status: string = "",
  ) {
    // this.domain = "test.com";
    // this.name = "John Doe";
    // this.phone = "123123123";
    // this.email = "john@test.com";
    // this.reason = "Customer was reporting none of his users could receive emails";
    // this.identification = "The customer's domain is missing MX records since it's a new account";
    // this.reasoning = "We went through the MX records setup";
    // this.secondary = "-Advised MX records aren't pointing to Google \n -Guided through DNS host on adding G Suite MX records \n -Advised 24-72 hours propagation time";
    // this.resolution = "Assisted customer on configuring G Suite MX records";
    // this.pinVerification = `PIN VALID: 
    // Specified PIN is Valid. It was generated by googleapps@psotago.org.nz with scope AS_SUPER_ADMIN. It expires at: 
    // 2019-Jul-07 22:51:29 L`;
    // this.emailVerification = `Resolving MX Record for google.com
    // Trying to connect to aspmx.l.google.com.
    // 220-mx.google.com ESMTP f10si7727479vsj.228 - gsmtp
    // EHLO googleapps.com
    // 250-mx.google.com at your service, [74.125.180.100]
    // SIZE 157286400
    // 8BITMIME
    // STARTTLS
    // ENHANCEDSTATUSCODES
    // PIPELINING
    // CHUNKING
    // SMTPUTF8
    // MAIL FROM:<noreply-smtptester@googleapps.com>
    // 250-2.1.0 OK f10si7727479vsj.228 - gsmtp
    // RCPT TO:<oreinosa@google.com>
    // 250-2.1.5 OK f10si7727479vsj.228 - gsmtp
    // QUIT
    // 221-2.0.0 closing connection f10si7727479vsj.228 - gsmtp
    // Connection terminated successfully`;
    // this.status = "Closed";
  }
}
